#![forbid(unsafe_code)]
//! A deterministic Markdown-vault generator: `(profile, seed)` in, a tree of
//! documents out.
//!
//! This crate produces *inputs*. It links nothing else in the workspace, reads
//! nothing the workspace produces, and has no opinion about what any of it
//! means — a generated tree is a pile of Markdown, and everything that reads
//! it is somebody else's code. That independence is why it can be trusted as a
//! measuring stick: a generator that shared a parser, a walker or a schema
//! with the system under test would measure the two together.
//!
//! # The determinism contract
//!
//! **The same `(profile, seed)` produces the same tree, byte for byte, on
//! every run and on every machine.** Concretely:
//!
//! - Every choice is drawn from a seeded generator, in a fixed order.
//! - No clock, environment variable, path, locale or hash-map iteration order
//!   reaches a generated byte. Timestamps in frontmatter are offsets from a
//!   fixed base date.
//! - Arithmetic is integer throughout, so no rounding difference can move a
//!   byte between platforms.
//! - Profiles are compile-time constants, so the pair really is the whole
//!   input.
//!
//! [`digest::tree`] turns a whole tree into one value, and the crate's
//! determinism suite asserts that two independent generations of each named
//! profile agree on it. Changing the generator changes the trees it produces:
//! that is allowed, and it is a reviewable act, not an accident. The contract
//! is that a *given* build is reproducible, and the suite is what keeps it so.
//!
//! ## What the contract does not bind
//!
//! It binds this crate's own profiles, going forward. It says nothing about
//! any tree generated by any other program: a recorded tree is reproduced from
//! its recording, never by asking this generator to regenerate it.
//!
//! # The five realism knobs
//!
//! Realism is not decoration. Every measurement taken against a generated tree
//! — walk cost, parse cost, memory, query plans, resolution behaviour — is
//! only as informative as the tree's resemblance to a real collection. The
//! knobs are the places that resemblance is dialled, and each is documented on
//! its own type in [`profile`]:
//!
//! 1. [`BodyShape`] — the body-length distribution.
//! 2. [`Ambiguity`] — how many stems repeat, and how large a class is.
//! 3. [`LinkDensity`] — links per document, their forms, and how many dangle.
//! 4. [`DirShape`] — the directory tree, placement within it, and leaf names.
//! 5. [`Clutter`] — non-Markdown files and directories holding none.
//!
//! ## Body length is the one that was most wrong
//!
//! A body drawn as a bounded uniform of a few short paragraphs averages a
//! couple of hundred bytes. A document in a real collection averages several
//! kilobytes, and the distribution is long-tailed: a large minority are much
//! longer than the median and a few are enormous. The gap is about twentyfold,
//! and it is not a cosmetic one — a tree of tiny documents understates every
//! per-byte cost by that factor, and it has no tail at all, so the largest
//! document a measurement ever sees is small. Peak memory, streaming
//! behaviour, and any cost that is a function of the biggest thing rather than
//! the average thing are invisible against such a tree.
//!
//! [`profile::LONG_TAILED_BODY`] is the answer: a weighted mixture whose mean
//! is about 4.5 KiB with a tail reaching 70 KiB, asserted as arithmetic in
//! that module's tests rather than left to prose. The calibration envelope in
//! [`probe`] is what keeps it there.
//!
//! # Calibration
//!
//! [`probe::measure`] reports a tree's shape statistics; [`probe::CALIBRATION`]
//! is the checked-in envelope they are expected to land in, with each range's
//! reasoning beside it. Recalibrating means editing that table — a reviewable
//! diff — never a value read from somewhere the repository cannot see. The
//! probe runs against any directory, so measuring a real collection and
//! comparing is a command, not a project.
//!
//! # Deliberate absences
//!
//! - **No vault configuration file is written.** What configuration a vault
//!   carries is a contract owned elsewhere and not yet made; guessing at it
//!   here would put an invented schema into every measurement tree. When that
//!   contract lands, emitting it becomes another knob.
//! - **No expected findings, codes or tiers.** This crate states what it
//!   generated, not what any program should conclude about it.
//! - **No symbolic links, and no filesystem exotica.** They belong to the
//!   crate that owns filesystem semantics, which can build them directly for
//!   the cases that need them.
//! - **No link-shaped text inside code fences.** Whether a fence hides a link
//!   from a parser is a syntax question, and answering it needs a document
//!   authored for that purpose rather than a statistical tree.

mod body;
mod clutter;
mod dates;
pub mod digest;
mod document;
mod layout;
mod links;
pub mod probe;
pub mod profile;
mod rng;
mod tree;
mod words;
mod yaml;

use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::Path;

pub use profile::{
    Ambiguity, BodyShape, Clutter, DirShape, LengthBucket, LinkDensity, PROFILES, Profile,
};

/// File marking a directory as generator-owned. Dot-prefixed, so a walk that
/// skips hidden entries never sees it.
pub const SENTINEL_FILE: &str = ".norn-fixture-vault";

/// Exact sentinel contents. A caller clearing a directory verifies these
/// bytes, and that the sentinel is a regular file rather than a link, before
/// deleting anything: a name-only check would let any stray file with the
/// right name authorise a recursive delete.
pub const SENTINEL_CONTENT: &str = "norn-fixtures generated vault — safe to delete\n";

/// What one generation produced.
///
/// The counts here are the generator's own account of its work. They are
/// facts about intent — how many links it made dangle, how large it made its
/// ambiguity classes — which is why they live here rather than in the probe,
/// which reads only bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Manifest {
    pub profile: &'static str,
    pub seed: u64,
    pub documents: usize,
    /// Every file written, documents and clutter and the sentinel alike.
    pub files: usize,
    pub directories: usize,
    pub markdown_bytes: usize,
    pub links: usize,
    pub dangling_links: usize,
    pub ambiguity_classes: usize,
    pub largest_ambiguity_class: usize,
}

impl Manifest {
    /// One line describing the generated tree.
    pub fn summary_line(&self) -> String {
        format!(
            "{} (seed {}): {} documents, {} files, {} directories, {} KiB of Markdown, \
             {} links ({} dangling), {} ambiguity classes up to k={}",
            self.profile,
            self.seed,
            self.documents,
            self.files,
            self.directories,
            self.markdown_bytes / 1024,
            self.links,
            self.dangling_links,
            self.ambiguity_classes,
            self.largest_ambiguity_class,
        )
    }
}

/// Mix a profile's name into its seed, so one seed produces unrelated trees
/// across profiles rather than parallel ones. FNV-1a over the name.
fn salt(name: &str) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in name.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

/// Accumulates the tree as it is written, so counts are exact rather than
/// re-derived by walking afterwards.
struct Writer<'a> {
    root: &'a Path,
    dirs: BTreeSet<String>,
    files: usize,
}

impl<'a> Writer<'a> {
    fn new(root: &'a Path) -> Self {
        Writer {
            root,
            dirs: BTreeSet::new(),
            files: 0,
        }
    }

    /// Create `rel` and every ancestor of it, recording each.
    fn ensure_dir(&mut self, rel: &str) -> io::Result<()> {
        if rel.is_empty() || self.dirs.contains(rel) {
            return Ok(());
        }
        fs::create_dir_all(self.root.join(rel))?;
        let mut prefix = String::new();
        for part in rel.split('/') {
            if !prefix.is_empty() {
                prefix.push('/');
            }
            prefix.push_str(part);
            self.dirs.insert(prefix.clone());
        }
        Ok(())
    }

    fn write(&mut self, rel: &str, bytes: &[u8]) -> io::Result<()> {
        if let Some((parent, _)) = rel.rsplit_once('/') {
            self.ensure_dir(parent)?;
        }
        fs::write(self.root.join(rel), bytes)?;
        self.files += 1;
        Ok(())
    }
}

/// Refuse anything but an absent or empty directory, and create it if absent.
fn prepare_out_dir(out_dir: &Path) -> io::Result<()> {
    match fs::metadata(out_dir) {
        Ok(meta) => {
            if !meta.is_dir() {
                return Err(io::Error::new(
                    io::ErrorKind::AlreadyExists,
                    format!("{} exists and is not a directory", out_dir.display()),
                ));
            }
            if fs::read_dir(out_dir)?.next().is_some() {
                return Err(io::Error::new(
                    io::ErrorKind::AlreadyExists,
                    format!("{} exists and is not empty", out_dir.display()),
                ));
            }
            Ok(())
        }
        Err(e) if e.kind() == io::ErrorKind::NotFound => fs::create_dir_all(out_dir),
        Err(e) => Err(e),
    }
}

/// Generate the tree `(profile, seed)` names, at `out_dir`.
///
/// `out_dir` must be absent or an empty directory; anything else is refused,
/// because generating into a populated directory produces a tree that is not a
/// function of the pair. The sentinel [`SENTINEL_FILE`] is written last.
pub fn generate(profile: &Profile, seed: u64, out_dir: &Path) -> io::Result<Manifest> {
    prepare_out_dir(out_dir)?;

    let mut rng = rng::Rng::new(seed ^ salt(profile.name));
    let mut writer = Writer::new(out_dir);

    // Every declared directory exists whether or not a document lands in it:
    // a walk pays for the directory, so the knob has to deliver it.
    let dirs = layout::directories(&profile.dirs);
    for dir in &dirs {
        writer.ensure_dir(dir)?;
    }
    for dir in clutter::empty_directories(&profile.clutter) {
        writer.ensure_dir(dir)?;
    }

    let plan = layout::plan(&mut rng, profile, &dirs);
    let (ambiguity_classes, largest_ambiguity_class) = layout::ambiguity_of(&plan);

    let mut markdown_bytes = 0;
    let mut total_links = 0;
    let mut dangling_links = 0;
    for (index, placed) in plan.iter().enumerate() {
        let links = links::draw(&mut rng, &profile.links, &plan, index);
        total_links += links.markup.len();
        dangling_links += links.dangling;
        let target = body::draw_length(&mut rng, &profile.body);
        let body = body::build(&mut rng, &profile.body, target, &links);
        let content = document::compose(&mut rng, profile, placed, &body);
        markdown_bytes += content.len();
        writer.write(&placed.path, content.as_bytes())?;
    }

    for file in clutter::files(&mut rng, &profile.clutter, plan.len(), &dirs) {
        writer.write(&file.path, &file.bytes)?;
    }

    writer.write(SENTINEL_FILE, SENTINEL_CONTENT.as_bytes())?;

    Ok(Manifest {
        profile: profile.name,
        seed,
        documents: plan.len(),
        files: writer.files,
        directories: writer.dirs.len(),
        markdown_bytes,
        links: total_links,
        dangling_links,
        ambiguity_classes,
        largest_ambiguity_class,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn salt_separates_the_profile_names() {
        let mut salts: Vec<u64> = Profile::names().iter().map(|n| salt(n)).collect();
        salts.sort_unstable();
        let total = salts.len();
        salts.dedup();
        assert_eq!(total, salts.len(), "two profiles share a salt");
    }

    #[test]
    fn the_sentinel_is_hidden() {
        assert!(SENTINEL_FILE.starts_with('.'));
        assert!(SENTINEL_CONTENT.ends_with('\n'));
    }
}
