#![forbid(unsafe_code)]
//! A deterministic Markdown-vault generator: `(profile, seed)` in, a tree of
//! documents out.
//!
//! This module set is the crate's foundation — a seeded generator, calendar
//! arithmetic, and a YAML scalar emitter. Each is small, each is exercised by
//! its own tests, and each exists here rather than as a dependency because the
//! crate is a zero-dependency leaf: a generator that links a random-number or
//! date crate inherits that crate's version drift into the trees every gate
//! measures against.
//!
//! They carry three properties the generator above them depends on:
//!
//! - **The PRNG is fixed.** Its algorithm is part of the determinism contract;
//!   changing it changes every generated tree.
//! - **Time comes from the seed.** Timestamps are offsets from a fixed base
//!   date, so no clock reaches a generated byte.
//! - **Interpolated YAML goes through one emitter**, so a pool or naming
//!   change cannot silently emit a value that YAML reparses into something
//!   else.

pub mod dates;
pub mod rng;
pub mod yaml;
